[env]
# When cargo is run from a subdirectory, this makes it behave as if it were run from the root.
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.wasm32-unknown-unknown]
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]
